grails-app/domain/com/baseball/AtBat.groovy
package com.baseball

/**
 * Created by patricktoner on 5/19/16.
 */
class AtBat {

    static constraints = {

        game(nullable:false, unique: ['num', 'eventNum'])
        year(nullable: false)
        eventNum(nullable:true)

        inningNum(nullable:false)
        inningTop(nullable:false)


        hitter(nullable:false)
        pitcher(nullable:false)

        startTimeUtc(nullable:true)

        num(nullable:true)
        balls(nullable:true)
        strikes(nullable:true)
        outs(nullable:true)

        description(nullable:true)
        event(nullable:true)

        score(nullable:true)
        awayTeamRuns(nullable:true)
        homeTeamRuns(nullable:true)

        baseRunner1Id(nullable:true)
        baseRunner2Id(nullable:true)
        baseRunner3Id(nullable:true)

        rbi(nullable:true)
        earnedRuns(nullable:true)

        pitcherHandedness(nullable:true)
        hitterHandedness(nullable:true)

        pitcherHomeAway(nullable:true)
        hitterHomeAway(nullable:true)

        pc(nullable:true)

        lastUpdated(nullable:true)
        dateCreated(nullable:true)

    }

    static mapping = {
        autoTimestamp(true)
        description sqlType: "text"
        game fetch: 'join', lazy: false
        hitter fetch: 'join', lazy: false
        pitcher fetch: 'join', lazy: false
    }

    Game game
    Integer year
    Integer eventNum
    Integer inningNum
    boolean inningTop


    Player hitter
    Player pitcher

    Date startTimeUtc

    Integer num
    Integer balls
    Integer strikes
    Integer outs

    String description
    String event

    boolean score
    Integer awayTeamRuns
    Integer homeTeamRuns

    Integer baseRunner1Id
    Integer baseRunner2Id
    Integer baseRunner3Id

    Integer rbi
    Integer earnedRuns

    String pitcherHandedness
    String hitterHandedness

    String pitcherHomeAway
    String hitterHomeAway

    Integer pc //pitchcount
    Integer pitchesBalls
    Integer pitchesStrikes


    Date lastUpdated
    Date dateCreated



    public boolean isSacFly() {
        return ("Sac Fly".equals(event))
    }

    public boolean isHit() {
        return ("Single".equals(event) || "Double".equals(event) || "Triple".equals(event) || "Home Run".equals(event))
    }

    public boolean isBB() {
        return ("Walk".equals(event) || "Intent Walk".equals(event))
    }

    public boolean isIBB() {
        return ("Intent Walk".equals(event))
    }


    public boolean isHpb() {
        return ("Hit By Pitch".equals(event))
    }

    public boolean isSingle() {
        return "Single".equals(event)
    }

    public boolean isDouble() {
        return "Double".equals(event)
    }

    public boolean isTriple() {
        return "Triple".equals(event)
    }

    public boolean isHr() {
        return "Home Run".equals(event)
    }

    public boolean isOut() {

    }

    public boolean isStrikeout() {
        return ("Strikeout".equals(event) || "Strikeout - DP".equals(event))
    }

    public boolean isAtBat() {

        if ("Intent Walk".equals(event)) return false
        if ("Hit By Pitch".equals(event)) return false
        if ("Sac Bunt".equals(event)) return false
        if ("Sac Fly".equals(event)) return false
        if ("Sac Fly DP".equals(event)) return false
        if ("Walk".equals(event)) return false
        if ("Catcher Interference".equals(event)) return false
        if ("Runner Out".equals(event)) return false
        if ("Ejection".equals(event)) return false

        return true

    }

    public boolean isPa() {
        if ("Ejection".equals(event)) return false
        if ("Runner Out".equals(event)) return false
        return true
    }


    public boolean isGroundBall() {
        if ("Bunt Groundout".equals(event)) return true
        if ("Grounded Into DP".equals(event)) return true
        if ("Groundout".equals(event)) return true
        if ("Fielders Choice".equals(event)) return true
        if ("Fielders Choice Out".equals(event)) return true
        if ("Force Out".equals(event)) return true
        if ("Sac Bunt".equals(event)) return true
        if ("Sacrifice Bunt DP".equals(event)) return true


        if (description?.contains(" ground ball ")) return true
        if (description?.contains(" grounds out ")) return true
        if (description?.contains(" grounds into ")) return true
    }

    public boolean isGroundOut() {
        return (groundBall && isAnOut())
    }


    public boolean isLineDrive() {

        if ("Lineout".equals(event)) return true
        if ("Bunt Lineout".equals(event)) return true
        if ("Bunt Pop Out".equals(event)) return true


        if (description?.contains(" line drive ")) return true
        if (description?.contains(" lines out ")) return true
        if (description?.contains(" lines into ")) return true
    }

    public boolean isLineOut() {
        return (lineDrive && isAnOut())
    }

    public boolean isFlyBall() {
        if ("Flyout".equals(event)) return true
        if ("Pop Out".equals(event)) return true
        if ("Sac Fly".equals(event)) return true
        if ("Sac Fly DP".equals(event)) return true

        if (description?.contains(" bunt pops ")) return true
        if (description?.contains(" pops out ")) return true
        if (description?.contains(" pops into ")) return true
        if (description?.contains(" flies out ")) return true
        if (description?.contains(" fly ball ")) return true
        if (description?.contains(" flies into ")) return true

        return false
    }

    public boolean isFlyOut() {
        return (flyBall && isAnOut())
    }

    public boolean isAnOut() {

        if ("Batter Interference".equals(event)) return true
        if ("Bunt Groundout".equals(event)) return true
        if ("Bunt Lineout".equals(event)) return true
        if ("Bunt Pop Out".equals(event)) return true
        if ("Fan interference".equals(event)) return true
        if ("Fielders Choice Out".equals(event)) return true
        if ("Flyout".equals(event)) return true
        if ("Forceout".equals(event)) return true
        if ("Grounded Into DP".equals(event)) return true
        if ("Groundout".equals(event)) return true
        if ("Lineout".equals(event)) return true
        if ("Pop Out".equals(event)) return true
        if ("Sac Bunt".equals(event)) return true
        if ("Sac Fly".equals(event)) return true
        if ("Sac Fly DP".equals(event)) return true
        if ("Sacrifice Bunt DP".equals(event)) return true
        if ("Strikeout".equals(event)) return true
        if ("Strikeout - DP".equals(event)) return true
        if ("Triple Play".equals(event)) return true

        return false
    }


}

grails-app/domain/com/baseball/HitterCareer.groovy
package com.baseball

import com.baseball.domain.HitterLog

/**
 * Created by patricktoner on 5/19/16.
 */
class HitterCareer extends HitterLog {

    static constraints = {
        importFrom HitterLog


        lastUpdated(nullable:true)
        dateCreated(nullable:true)

    }

    static mapping = {
        autoTimestamp(true)
        hitter fetch: 'join', lazy: false
    }


    Date lastUpdated
    Date dateCreated



    public Double getFanduelAvg() {
        if (games == null || games == 0 || fanduelPoints == null) return 0
        return fanduelPoints / games
    }

}

grails-app/domain/com/baseball/PitcherCareer.groovy
package com.baseball

import com.baseball.domain.PitcherLog

/**
 * Created by patricktoner on 5/19/16.
 */
class PitcherCareer extends PitcherLog{

    static constraints = {

        importFrom PitcherLog


        dateCreated(nullable:true)
        lastUpdated(nullable:true)
    }

    static mapping = {
        autoTimestamp(true)
        pitcher fetch: 'join', lazy: false
    }




    Date dateCreated
    Date lastUpdated



    public String getIp() {

        int fullIp = outs / 3
        int remainder = outs % 3

        return fullIp + "." + remainder


    }

    public Double getFanduelAvg() {
        if (games == null || games == 0 || fanduelPoints == null) return 0
        return fanduelPoints / games
    }



}

grails-app/domain/com/baseball/Player.groovy
package com.baseball

import com.baseball.PlayerService

/**
 * Created by patricktoner on 5/21/16.
 */
class Player {

    def playerService

    static constraints = {

        gamedayId(nullable:false, unique: true, maxSize: 40)
        fanduelId(nullable:true)
        rotogrinderId(nullable:true)

        firstName(nullable:false)
        lastName(nullable:false)
        displayName(nullable:true)

        currentTeam(nullable:true)

        pitches(nullable:true)
        bats(nullable:true)

        position(nullable:false)
        currentPosition(nullable:false)

        status(nullable:true)

        last10FantasyPoints(nullable:true)
        seasonAvgFantasyPoints(nullable:true)
        seasonFloorFantasyPoints(nullable:true)
        seasonCeilingFantasyPoints(nullable:true)

        lastUpdated(nullable:true)
        dateCreated(nullable:true)

    }

    static mapping = {
        autoTimestamp(true)
        cache true
    }

    String gamedayId
    String fanduelId
    Integer rotogrinderId

    String firstName
    String lastName
    String displayName

    Team currentTeam

    String pitches
    String bats

    String position
    String currentPosition

    String status

    Double last10FantasyPoints
    Double seasonAvgFantasyPoints
    Double seasonFloorFantasyPoints
    Double seasonCeilingFantasyPoints

    Date lastUpdated
    Date dateCreated




    public String getFullName() {
        return firstName + " " + lastName
    }

    public String getAbbrevName() {
        return lastName + ", " + firstName.take(1)
    }

    public getPermaLink() {
        return playerService.getPermaLink(this)
    }


    public getFanduelPosition() {
        if ("CF".equals(position) || "LF".equals(position) || "RF".equals(position)) return "OF"
        return position
    }


}

grails-app/domain/com/baseball/Runner.groovy
package com.baseball

class Runner {

    static constraints = {
        atBat(nullable:false)
        start(nullable:true)
        end(nullable:true)
        event(nullable:true)
        eventNum(nullable:true)
    }

    static mapping = {
        autoTimestamp true
    }


    AtBat atBat

    String start
    String end
    String event
    boolean score
    boolean earned
    Integer eventNum

    Date lastUpdated
    Date dateCreated


    public boolean isBalk() {
        return "Balk".equals(event)
    }

    public boolean isCatcherInterference() {
        return "Catcher Interference".equals(event)
    }

    public boolean isCs() {
        return "Caught Stealing 2B".equals(event)
        return "Caught Stealing 3B".equals(event)
        return "Caught Stealing Home".equals(event)
    }

    public boolean isDoublePlay() {
        return "Double Play".equals(event)
        return "Grounded Into DP".equals(event)
    }

    public boolean isHbp() {
        return "Hit By Pitch".equals(event)
    }

    public boolean isHomeRun() {
        return "Home Run".equals(event)
    }

    public boolean isIbb() {
        return "Intent Walk".equals(event)
    }

    public boolean isBb() {
        return "Walk".equals(event) || isIbb()
    }

    public boolean isLineout() {
        return "Lineout".equals(event)
    }

    public boolean isPassedBall() {
        return "Passed Ball".equals(event)
    }

    public boolean isPickoffStealing() {
        return "Picked off stealing 2B".equals(event)
        return "Picked off stealing 3B".equals(event)
        return "Picked off stealing home".equals(event)
    }


    public boolean isPickoff() {
        return "Picked off stealing 2B".equals(event)
        return "Picked off stealing 3B".equals(event)
        return "Picked off stealing home".equals(event)
        return "Pickoff 1B".equals(event)
        return "Pickoff 3B".equals(event)
    }

    public boolean isPickoffAttempt() {
        return "Pickoff Attempt 1B".equals(event)
        return "Pickoff Attempt 2B".equals(event)
        return "Pickoff Attempt 3B".equals(event)
    }

    public boolean isPickoffError() {
        return "Pickoff Error 1B".equals(event)
        return "Pickoff Error 2B".equals(event)
        return "Pickoff Error 3B".equals(event)
    }


    public boolean isPopout() {
        return "Pop Out".equals(event)
    }


    public boolean isRunnerInterference() {
        return "Runner Interference".equals(event)
    }

    public boolean isRunnerOut() {
        return "Runner Out".equals(event)
    }

    public boolean isSacBunt() {
        return "Sac Bunt".equals(event)
    }

    public boolean isSacFly() {
        return "Sac Fly".equals(event)
    }


    public boolean isSacFlyDp() {
        return "Sac Fly DP".equals(event)
    }

    public boolean isSingle() {
        return "Single".equals(event)
    }

    public boolean isStolenBase() {
        return "Stolen Base 2B".equals(event)
        return "Stolen Base 3B".equals(event)
        return "Stolen Base Home".equals(event)
    }


    public boolean isStrikeout() {
        return "Strikeout".equals(event)
        return "Strikeout - DP".equals(event)
    }

    public boolean isTriple() {
        return "Triple".equals(event)
    }



//
//
//
//
//
//
//    Wild Pitch




//    Bunt Groundout
//    Defensive Indiff
//    Double
//    Error
//    Fan interference
//    Field Error
//    Fielders Choice
//    Fielders Choice Out
//    Flyout
//    Forceout



}

grails-app/views/player/_hitting_seasons_table.gsp
<table class="table table-bordered stats hitting">

    <tr>
        <th>Year</th>
        <th>G</th>
        <th>PA</th>
        <th>AB</th>
        <th>R</th>
        <th>H</th>
        <th>2B</th>
        <th>3B</th>
        <th>HR</th>
        <th>RBI</th>
        <th>SB</th>
        <th>CS</th>
        <th>BB</th>
        <th>SO</th>
        <th>BA</th>
        <th>OBP</th>
        <th>SLG</th>
        <th>OPS</th>
        <th class="advanced">TB</th>
        <th class="advanced">GDP</th>
        <th>HPB</th>
        <th class="advanced">SH</th>
        <th class="advanced">SF</th>
        <th class="advanced">IBB</th>

        <th class="advanced">LOB</th>
        <th class="advanced">GO</th>
        <th class="advanced">FO</th>
        <th>K%</th>
        <th>BB%</th>
        <th>ISO</th>

        <th>wOBA</th>
        <th>wFDA</th>

        <th>FD</th>
        <th>FDAvg</th>
    </th>
    </tr>

    <g:each in="${hittingSeasons}" var="hittingSeason">
        <tr>
            <td>
                <a href="/player/hittingLog?id=${player.id}&year=${hittingSeason.year}">${hittingSeason.year}</a>
            </td>

            <td>${hittingSeason.games}</td>
            <td>${hittingSeason.pa}</td>
            <td>${hittingSeason.atBats}</td>
            <td>${hittingSeason.runs}</td>
            <td>${hittingSeason.hits}</td>
            <td>${hittingSeason.doubles}</td>
            <td>${hittingSeason.triples}</td>
            <td>${hittingSeason.homeRuns}</td>
            <td>${hittingSeason.rbi}</td>
            <td>${hittingSeason.sb}</td>
            <td>${hittingSeason.cs}</td>
            <td>${hittingSeason.bb}</td>
            <td>${hittingSeason.so}</td>
            <td>${hittingSeason.avg?.formatThree()}</td>
            <td>${hittingSeason.obp?.formatThree()}</td>
            <td>${hittingSeason.slg?.formatThree()}</td>
            <td>${hittingSeason.ops?.formatThree()}</td>
            <td class="advanced">${hittingSeason.tb}</td>
            <td class="advanced">${hittingSeason.gidp}</td>
            <td>${hittingSeason.hbp}</td>
            <td class="advanced">${hittingSeason.sacBunts}</td>
            <td class="advanced">${hittingSeason.sacFlys}</td>
            <td class="advanced">${hittingSeason.ibb}</td>

            <td class="advanced">${hittingSeason.lob}</td>

            <td class="advanced">${hittingSeason.groundOuts}</td>
            <td class="advanced">${hittingSeason.flyOuts}</td>
            <td>${hittingSeason.soPercent?.formatPercent()}</td>
            <td>${hittingSeason.bbPercent?.formatPercent()}</td>
            <td>${hittingSeason.iso?.formatThree()}</td>
            <td>${hittingSeason.wOba?.formatThree()}</td>
            <td>${hittingSeason.wFda?.formatTwo()}</td>

            <td>${hittingSeason.fanduelPoints?.formatTwo()}</td>
            <td>${hittingSeason.fanduelAvg?.formatTwo()}</td>

        </tr>

    </g:each>

    <tr class="total">
        <td>
            Total
        </td>

        <td>${hitterCareer.games}</td>
        <td>${hitterCareer.pa}</td>
        <td>${hitterCareer.atBats}</td>
        <td>${hitterCareer.runs}</td>
        <td>${hitterCareer.hits}</td>
        <td>${hitterCareer.doubles}</td>
        <td>${hitterCareer.triples}</td>
        <td>${hitterCareer.homeRuns}</td>
        <td>${hitterCareer.rbi}</td>
        <td>${hitterCareer.sb}</td>
        <td>${hitterCareer.cs}</td>
        <td>${hitterCareer.bb}</td>
        <td>${hitterCareer.so}</td>
        <td>${hitterCareer.avg?.formatThree()}</td>
        <td>${hitterCareer.obp?.formatThree()}</td>
        <td>${hitterCareer.slg?.formatThree()}</td>
        <td>${hitterCareer.ops?.formatThree()}</td>
        <td class="advanced">${hitterCareer.tb}</td>
        <td class="advanced">${hitterCareer.gidp}</td>
        <td>${hitterCareer.hbp}</td>
        <td class="advanced">${hitterCareer.sacBunts}</td>
        <td class="advanced">${hitterCareer.sacFlys}</td>
        <td class="advanced">${hitterCareer.ibb}</td>

        <td class="advanced">${hitterCareer.lob}</td>

        <td class="advanced">${hitterCareer.groundOuts}</td>
        <td class="advanced">${hitterCareer.flyOuts}</td>
        <td>${hitterCareer.soPercent?.formatPercent()}</td>
        <td>${hitterCareer.bbPercent?.formatPercent()}</td>
        <td>${hitterCareer.iso?.formatThree()}</td>
        <td>${hitterCareer.wOba?.formatThree()}</td>
        <td>${hitterCareer.wFda?.formatTwo()}</td>
        <td>${hitterCareer.fanduelPoints?.formatTwo()}</td>
        <td>${hitterCareer.fanduelAvg?.formatTwo()}</td>

    </tr>


    <tr class="total">
        <td>
            Park Adj.
        </td>

        <td>${hitterCareer.games}</td>
        <td>${hitterCareer.pa}</td>
        <td>${hitterCareer.atBats}</td>
        <td>${hitterCareer.paRuns?.formatTwo()}</td>
        <td>${hitterCareer.paHits?.formatTwo()}</td>
        <td>${hitterCareer.paDoubles?.formatTwo()}</td>
        <td>${hitterCareer.paTriples?.formatTwo()}</td>
        <td>${hitterCareer.paHomeRuns?.formatTwo()}</td>
        <td>${hitterCareer.paRbi?.formatTwo()}</td>
        <td>${hitterCareer.paSb?.formatTwo()}</td>
        <td>${hitterCareer.paCs?.formatTwo()}</td>
        <td>${hitterCareer.paBb?.formatTwo()}</td>
        <td>${hitterCareer.paSo?.formatTwo()}</td>
        <td>${hitterCareer.paAvg?.formatThree()}</td>
        <td>${hitterCareer.paObp?.formatThree()}</td>
        <td>${hitterCareer.paSlg?.formatThree()}</td>
        <td>${hitterCareer.paOps?.formatThree()}</td>
        <td class="advanced">${hitterCareer.paTb}</td>
        <td class="advanced">${hitterCareer.gidp}</td>
        <td>${hitterCareer.hbp}</td>
        <td class="advanced">${hitterCareer.paSacBunts}</td>
        <td class="advanced">${hitterCareer.paSacFlys}</td>
        <td class="advanced">${hitterCareer.paIbb}</td>

        <td class="advanced">${hitterCareer.lob}</td>

        <td class="advanced">${hitterCareer.groundOuts}</td>
        <td class="advanced">${hitterCareer.flyOuts}</td>
        <td>${hitterCareer.soPercent?.formatPercent()}</td>
        <td>${hitterCareer.bbPercent?.formatPercent()}</td>
        <td>${hitterCareer.paIso?.formatThree()}</td>
        <td>${hitterCareer.paWOba?.formatThree()}</td>
        <td>${hitterCareer.paWFda?.formatTwo()}</td>

        <td>${hitterCareer.fanduelPoints?.formatTwo()}</td>
        <td>${hitterCareer.fanduelAvg?.formatTwo()}</td>

    </tr>



</table>

grails-app/views/player/hittingLog.gsp
<g:applyLayout name="main">

    <head>

    </head>





    <content tag="content">

        <h1><a href="/player/show/${player.id}">${player.fullName}</a> <small>${year}</small></h1>




        <g:if test="${gameLogList.size() > 0}">
            <h2>Game Log</h2>
            <table class="table table-bordered stats">

                <tr>
                    <th>Date</th>
                    <th>AB</th>
                    <th>H</th>
                    <th>1B</th>
                    <th>2B</th>
                    <th>3B</th>
                    <th>HR</th>
                    <th>R</th>
                    <th>RBI</th>
                    <th>BB</th>
                    <th>HPB</th>
                    <th>SB</th>
                    <th>CS</th>

                    <th>HPB</th>
                    <th>SO</th>
                    <th>LOB</th>
                    <th>SAC B</th>
                    <th>SAC F</th>
                    <th>GO</th>
                    <th>FO</th>
                    <th>GIDP</th>
                    <th>.AVG</th>

                    <th>FD</th>
                </th>
                </tr>

                <g:each in="${gameLogList}" var="gameLog">
                    <tr>
                        <td>
                            <g:formatDate format="yyyy-MM-dd" date="${gameLog.game.startDate}"/>
                        </td>

                        <td>${gameLog.atBats}</td>
                        <td>${gameLog.hits}</td>
                        <td>${gameLog.singles}</td>
                        <td>${gameLog.doubles}</td>
                        <td>${gameLog.triples}</td>
                        <td>${gameLog.homeRuns}</td>
                        <td>${gameLog.runs}</td>
                        <td>${gameLog.rbi}</td>
                        <td>${gameLog.bb}</td>
                        <td>${gameLog.hbp}</td>
                        <td>${gameLog.sb}</td>
                        <td>${gameLog.cs}</td>

                        <td>${gameLog.hbp}</td>
                        <td>${gameLog.so}</td>
                        <td>${gameLog.lob}</td>
                        <td>${gameLog.sacBunts}</td>
                        <td>${gameLog.sacFlys}</td>
                        <td>${gameLog.groundOuts}</td>
                        <td>${gameLog.flyOuts}</td>
                        <td>${gameLog.gidp}</td>

                        <td>${gameLog.avg?.formatThree()}</td>
                        <td>${gameLog.fanduelPoints?.formatTwo()}</td>
                    </tr>

                </g:each>
            </table>
        </g:if>



    </content>



</g:applyLayout>

grails-app/views/player/popupPitcher.gsp
<div class="container">
    <div class="row">


        <h3><a href="${player.permaLink}">${player.fullName} <small>${player.currentTeam.abbrev} ${player.currentPosition}</small></a></h3>

        <h5>${pitcherSeason?.year} Season</h5>
        <table cellspacing="0" cellpadding="0" border="0" id="pc" class="table table-bordered hitter-season-summary">
            <tbody>
                <tr>
                    <th title="W-L">W-L</th>
                    <th title="SV">SV</th>
                    <th title="K">K</th>
                    <th title="ERA">ERA</th>
                    <th title="wFDA">wFDA</th>
                    <th title="Fandeul Points">FD</th>
                </tr>
                <tr>
                    <td>${pitcherSeason?.wins} - ${pitcherSeason?.losses}</td>
                    <td>${pitcherSeason?.saves}</td>
                    <td>${pitcherSeason?.so}</td>
                    <td>${pitcherSeason?.era?.formatTwo()}</td>
                    <td>${pitcherSeason?.opponentWFda?.formatThree()}</td>
                    <td>${pitcherSeason?.fanduelAvg?.formatTwo()}</td>
                </tr>
            </tbody>
        </table>


        %{--<h5>${pitcherSeason.year} Splits</h5>--}%
        %{--<table cellspacing="0" cellpadding="0" border="0" id="pc" class="table table-bordered hitter-season-summary">--}%
            %{--<tbody>--}%
                %{--<tr>--}%
                    %{--<th title="Split">Split</th>--}%
                    %{--<th title="PA">PA</th>--}%
                    %{--<th title="Batting Average">AVG</th>--}%
                    %{--<th title="Runs Scored">R</th>--}%
                    %{--<th title="Home Runs">HR</th>--}%
                    %{--<th title="Runs Batted In">RBI</th>--}%
                    %{--<th title="Stolen Bases">SB</th>--}%
                    %{--<th title="wFDA">wFDA</th>--}%
                    %{--<th title="FD">FD</th>--}%
                %{--</tr>--}%

                %{--<tr><th colspan="9">Handedness</th></tr>--}%
                %{--<g:each in="${hittingSeasonSplits.findAll { it.isHandedness() }}" var="hitterSeasonSplit">--}%
                    %{--<g:render template="hitting_splits_row" model="[hitterSeasonSplit: hitterSeasonSplit]" />--}%
                %{--</g:each>--}%


                %{--<tr><th colspan="9">Home/Road</th></tr>--}%
                %{--<g:each in="${hittingSeasonSplits.findAll { it.isHomeAway() }}" var="hitterSeasonSplit">--}%
                    %{--<g:render template="hitting_splits_row" model="[hitterSeasonSplit: hitterSeasonSplit]" />--}%
                %{--</g:each>--}%


                %{--<tr><th colspan="9">Recent</th></tr>--}%
                %{--<g:each in="${hittingSeasonSplits.findAll { it.isRecent() }}" var="hitterSeasonSplit">--}%
                    %{--<g:render template="hitting_splits_row" model="[hitterSeasonSplit: hitterSeasonSplit]" />--}%
                %{--</g:each>--}%


            %{--</tbody>--}%
        %{--</table>--}%





        <h5>Recent Games</h5>
        <table cellspacing="0" cellpadding="0" border="0" id="pc2"  class="table table-bordered hitter-recent-gamelog">
            <tbody>
                <tr>
                    <th title="Date" >DATE</th>
                    <th title="Opponent">OPP</th>
                    <th title="IP">IP</th>
                    <th title="H">H</th>
                    <th title="HR">HR</th>
                    <th title="ER">ER</th>
                    <th title="BB">BB</th>
                    <th title="K">K</th>
                    <th title="DEC">DEC</th>
                    <th title="Fantasy Points">FD</th>
                </tr>
                <g:each in="${recentGameLogs}" var="recentGameLog">
                    <tr>
                        <td>${recentGameLog.game.startDate.format("M/dd")}</td>
                        <td>${recentGameLog.opponent.abbrev}</td>
                        <td>${recentGameLog.ip}</td>
                        <td>${recentGameLog.h}</td>
                        <td>${recentGameLog.hr}</td>
                        <td>${recentGameLog.er}</td>
                        <td>${recentGameLog.bb}</td>
                        <td>${recentGameLog.so}</td>
                        <td>${recentGameLog.wins ? 'W' : ''}${recentGameLog.losses ? 'L' : ''}</td>
                        <td align="right">${recentGameLog.fanduelPoints}</td>
                    </tr>
                </g:each>

            </tbody>
        </table>



    </div>
</div>